apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
    environment: "{{ .Values.environment }}"
    version: "{{ .Values.version }}"
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.config.port }}
      targetPort: 3000
      nodePort: {{ .Values.deployment.nodePort }}